set(_CATKIN_CURRENT_PACKAGE "motion_control_package")
set(motion_control_package_VERSION "0.0.0")
set(motion_control_package_MAINTAINER "yang <yang@todo.todo>")
set(motion_control_package_PACKAGE_FORMAT "2")
set(motion_control_package_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(motion_control_package_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(motion_control_package_BUILDTOOL_DEPENDS "catkin")
set(motion_control_package_BUILDTOOL_EXPORT_DEPENDS )
set(motion_control_package_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(motion_control_package_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(motion_control_package_TEST_DEPENDS )
set(motion_control_package_DOC_DEPENDS )
set(motion_control_package_URL_WEBSITE "")
set(motion_control_package_URL_BUGTRACKER "")
set(motion_control_package_URL_REPOSITORY "")
set(motion_control_package_DEPRECATED "")