set(_CATKIN_CURRENT_PACKAGE "miro2_msg")
set(miro2_msg_VERSION "0.1.0")
set(miro2_msg_MAINTAINER "CqR Labs <labs@consequentialrobotics.com>")
set(miro2_msg_PACKAGE_FORMAT "2")
set(miro2_msg_BUILD_DEPENDS "message_generation" "message_runtime" "rospy")
set(miro2_msg_BUILD_EXPORT_DEPENDS "rospy")
set(miro2_msg_BUILDTOOL_DEPENDS "catkin")
set(miro2_msg_BUILDTOOL_EXPORT_DEPENDS )
set(miro2_msg_EXEC_DEPENDS "message_runtime" "rospy" "python-opencv" "python-numpy" "message_generation")
set(miro2_msg_RUN_DEPENDS "message_runtime" "rospy" "python-opencv" "python-numpy" "message_generation")
set(miro2_msg_TEST_DEPENDS )
set(miro2_msg_DOC_DEPENDS )
set(miro2_msg_URL_WEBSITE "")
set(miro2_msg_URL_BUGTRACKER "")
set(miro2_msg_URL_REPOSITORY "")
set(miro2_msg_DEPRECATED "")